Repository FIRSTPLATO/unlock-huawei-e5830-e5832, pull requests merged in 2020-10, with the labels that each got.

#1 Commit pertamaku (readme, readme_en, upload pics)
  CONTRIBUTING.md
  README.md
  README_en.md
  img/.list
  img/e5830-1-driver.PNG
  img/e5830-2-driver.PNG
Labels: documentation, good first issue, hacktoberfest-accepted

#2 unlock-huawei-e5830-e5832 - advantages update
  README.md
  README_en.md
  img/1.jpg
Labels: documentation, hacktoberfest-accepted

#3 Update docs and add some screenshots for some features provided by lastest firmware
  README.md
  README_en.md
  img/1.png
  img/2.png
  img/3.png
  img/4.png
  img/5.png
  img/6.png
Labels: documentation, hacktoberfest-accepted

#4 update preview with another provider
  README.md
  img/7.png
Labels: documentation, hacktoberfest-accepted, help wanted
